### ISSUE TITLE
Cyclesgame website links to GitHub homepage instead of repository

### ISSUE THREAD

**Issue by dstrekelj** [luboslenco/cyclesgame#2]
Hello,

It's not exactly an issue, but the GitHub link on the [cyclesgame](http://cyclesgame.org/) website links to http://github.com instead of the expected repo URL (https://github.com/luboslenco/cyclesgame). Just thought I'd let you know in case this isn't intended behaviour.

Great work, by the way! Big fan ever since zBlend. Keep it up :)

**Comment by luboslenco** [comment]
Hey,

It was indeed intended but now I realize it is only confusing. I left it out as there are still no docs - please keep the issue open:)

Happy to hear that, keeps motivation up! I checked out your odd renderer, that is looking super sweet too!

**Comment by dstrekelj** [comment]
Makes sense! I'll keep it open then. :)

And thanks for the kind comment! Means a lot!

**Comment by luboslenco** [comment]
Forgot to close - although the website is still crap, at least the link to GitHub is now fixed.
