### ISSUE TITLE
Project build error: debug-html5-resources/deferred_AlphaTest_Billboard.vert.essl: No such file or directory

### ISSUE THREAD

**Issue by KosLooney** [luboslenco/cyclesgame#4]
Hi Lubos,

Read your post on blenderartist and I got triggered to check out your work. The videos are looking awesome.

I'm encountering some startup issues on the way. The first three are minor and I got passed those.
The last one got me stuck.

**1.Getting an error in blender when pressing the start button:**
![image](https://cloud.githubusercontent.com/assets/18315413/14761933/18e71be4-096e-11e6-910c-32305b2aa989.png)

I guess it's Windows based. Temp fixed it by altering cyclesgame.py:
`87 output = subprocess.check_output([haxelib_path, 'path', 'cyclesgame'], shell=True)`
After that I also had to split the output on \r instead of \n
`88  output = str(output).split("\\r")[0].split("'")[1]`

**2.Compiling the shaders doesn't work when pressing the build button.**
Same issue as above. Temp fixed it by altering project.py:
```
197 output = subprocess.check_output([haxelib_path, 'path', 'cyclesgame'], shell=True)
198 output = str(output).split("\\r")[0].split("'")[1]
```

**3.On building a project, using the latest kha[16.1.2] build, there are some reference errors:**
```
C:\HaxeToolkit\haxe\lib\lue\git\Sources/lue/resource/ShaderResource.hx:14: characters 7-35 : Type not found : kha.graphics4.BlendingFactor
..\Sources/Main.hx:3: lines 3-38 : Defined in this class
C:\HaxeToolkit\haxe\lib\lue\git\Sources/lue/resource/PipelineResource.hx:5: characters 7-39 : Type not found : kha.graphics4.DepthStencilFormat
..\Sources/Main.hx:3: lines 3-38 : Defined in this class
```
Using your Kha fork fixed these.

**4. On building a project there is missing a file: deferred_AlphaTest_Billboard.vert.essl**

1. Copied the compiled folder to the Sources/Shaders folder
2. Run haxelib run kha html5

Getting alot of debug ouput:
```
SPIRV is not generated for failed compile or link
ERROR: 0:325: 'texCoord' : undeclared identifier 
ERROR: 0:325: 'texture' : no matching overloaded function found 
ERROR: 2 compilation errors.  No code generated.


SPIRV is not generated for failed compile or link
ERROR: 0:326: 'texCoord' : undeclared identifier 
ERROR: 0:326: 'texture' : no matching overloaded function found 
ERROR: 2 compilation errors.  No code generated.
```

Eventually:

```
Assets done.
c:\Users\gebruiker\Documents\Kha\Kha\Tools\haxe\std/neko/_std/sys/io/File.hx:30: characters 20-51 : debug-html5-resources/deferred_AlphaTest_Billboard.vert.essl: No such file or directory
c:\Users\gebruiker\Documents\Kha\Kha\Tools\haxe\std/neko/_std/sys/io/File.hx:34: characters 33-49 : Called from
c:\Users\gebruiker\Documents\Kha\Kha\Sources/kha/internal/ShadersBuilder.hx:27: characters 36-96 : Called from
c:\Users\gebruiker\Documents\Kha\Kha\Sources/kha/Shaders.hx:33: characters 2-7 : Called from
Aborted
Done.
Failed to load resource: net::ERR_FILE_NOT_FOUND (file:///C:/Users/gebruiker/Documents/Kha/build/debug-html5/kha.js)
```

build\debug-html5-resources is filled with essl files, but deferred_AlphaTest_Billboard.vert.essl is indeed missing.

**Current setup:**

- Blender 2.77a
- Windows 10
- Kode Studio 1.6.1

- haxe: [3.2.1]
- kha: [16.1.2]
- cyclesgame: git [dev:C:\HaxeToolkit\haxe\lib/cyclesgame/git]
- lue: git [dev:C:\HaxeToolkit\haxe\lib/lue/git]

**Comment by luboslenco** [comment]
Hello Kos,

Wow, happy that you got interested in the project. Give me a little more time to fix the build process. I want to rework it completely - having a single SDK that you can just point to and have everything up and running without any additional dependencies. These notes will all come handy, sorry for the troubles. :)

**Comment by luboslenco** [comment]
Closing for now - will provide a complete getting started guide.
