### ISSUE TITLE
Toon Shader Support

### ISSUE THREAD

**Issue by zauberparacelsus** [luboslenco/cyclesgame#5]
Would it be possible to support the toon shader nodes?  And if so, would it also be possible to do so with some form of edge/outline rendering?

**Comment by luboslenco** [comment]
Basic toon shader is in, will improve over time. The outline detect is not good enough, will eventually provide separate outline pass in compositor, which will be usable for any shaders. For now, this is a start. :)

![toon](https://cloud.githubusercontent.com/assets/3685704/15081473/782ac718-13c3-11e6-8cb9-7d30bc6892f2.jpg)
